---
# Required to ensure containers continue to run even after logout
# https://www.redhat.com/en/blog/container-systemd-persist-reboot
- name: Enable Linger for user - {{ ansible_user }}
  ansible.builtin.command:
    argv:
      - /usr/bin/loginctl
      - enable-linger
      - "{{ ansible_user }}"
    creates: "/var/lib/systemd/linger/{{ ansible_user }}"
