- name: Install node exporter
  hosts: all
  gather_facts: false

  tasks:

    - name: Install node exporter
      ansible.builtin.include_role:
        name: grafana
        tasks_from: node_exporter
